### ISSUE TITLE
No file "stamp-OpenAVRc.h"

### ISSUE THREAD

**Issue by stanekTM** [Ingwie/OpenAVRc_Dev#12]
The header file is missing when assembled from the main "simulator" source.
Thanks George  :eagle: 

![Capture202041-0](https://user-images.githubusercontent.com/44894972/78181110-208ec300-7464-11ea-9dd4-c8e1349dcafe.png)

**Comment by Ingwie** [comment]
This file (Stamp-OpenAVRc.h) is created by the makefile of the firmware.
Build a firmware (do not clean it) and build the Simu ;-)

**Comment by stanekTM** [comment]
Oh yes, but I still have a mistake, these files are certainly in processing, I will use the original sources.
Thank you George :key: 
![Capture202042-0](https://user-images.githubusercontent.com/44894972/78186818-ab27f000-746d-11ea-9635-25c90f878ed7.png)

**Comment by Ingwie** [comment]
I commit the correct file in one minute ....

**Comment by Ingwie** [comment]
PierroTM777 tell me about this missing update : OUPS !

**Comment by stanekTM** [comment]
I'm sorry Christophe :gear: 
![Capture202042-0](https://user-images.githubusercontent.com/44894972/78189170-d7de0680-7471-11ea-8ffb-c436634547e1.png)

**Comment by Ingwie** [comment]
No no, I think the wxsmith files are not updated : I work on a lot of part of the project at this time and miss some update.
One (last) minute please...

**Comment by stanekTM** [comment]
Don't hurry Christophe,
can i translate translate to "setup.exe" from you.
When you build your update, I'll be happy to try everything.
I'm your servant  :yin_yang: 
George

**Comment by Ingwie** [comment]
Yes, do what you want....
Another job for me : An updated "builder" :+1:  .. in construction

**Comment by Ingwie** [comment]
Link -> https://codeblocks.org/

**Comment by stanekTM** [comment]
Thank you, I will explore this as a beginner, I need a syntax fix and the help I have with the visual studio that helps me with the Windows API and C ++.
Every day I enjoy OpenAVRc in the living room, race, polish the floor :czech_republic:

**Comment by pierrotm777** [comment]
Je regarde ça ce matin. A+

**Comment by stanekTM** [comment]
Thank you guys,
Already OK. I am the happiest owner of OpenAVRc :+1:
