### ISSUE TITLE
Protocol J6PRO doesn't work.

### ISSUE THREAD

**Issue by sloped-soarer** [Ingwie/OpenAVRc_Dev#36]
Cant get the Protocol to work. Anybody else tested the Nine Eagles J6Pro protocol.

**Comment by Ingwie** [comment]
Hi Rich,

I don't have a receiver -> Never tested here ...

**Comment by pierrotm777** [comment]
Not this receiver. Never tested. Sorry.

**Comment by pierrotm777** [comment]
MultiProtocol 4in1 modules accept the J6Pro protocol (code 22).

**Comment by testeur68** [comment]
No sorry, I don't use this protocol, only Frsky receivers. JPEnvoyé depuis mon téléphone Huawei-------- Message original --------De : sloped-soarer <notifications@github.com>Date : mer. 16 sept. 2020 à 19:40À : Ingwie/OpenAVRc_Dev <OpenAVRc_Dev@noreply.github.com>Cc : Subscribed <subscribed@noreply.github.com>Objet : [Ingwie/OpenAVRc_Dev] Protocol J6PRO doesn't work. (#36)
Cant get the Protocol to work. Anybody else tested the Nine Eagles J6Pro protocol.

**Comment by sloped-soarer** [comment]
Thank You for Your replies.
My CYRF6936 SPI module works with Devo protocol and the receiver works with the J6PRO protocol selected via MultiProtocol 4in1 (Orange RX) module. So it must be the SPI protocol that has a bug.

I think this might take a while to fix. I'm thinking about putting the logic analyser on the old J6PRO transmitter and starting again.

**Comment by Ingwie** [comment]
Hi, Yes, please do that Rich.

Whithout develloper like you : OpenAVRc never grown.

B.R. Christophe

**Comment by sloped-soarer** [comment]
Okay ... It looks like J6PRO likes the CYRF manufacture id and not the Transmitter RF ID.
I just want to fly My old Heli.
Christophe. I will send You an email when My head is clear.

**Comment by sloped-soarer** [comment]
I have a working protocol. Github to be updated.
