### ISSUE TITLE
Cant get OrangeRx R614XN to bind in DSMX mode.

### ISSUE THREAD

**Issue by sloped-soarer** [Ingwie/OpenAVRc_Dev#66]
Does anyone use DSMX 22ms ?.
I can't get this receiver to bind in DSMX 22ms mode. DSM2 22ms is okay though.

https://hobbyking.com/en_us/orangerx-r614xn-dsm2-dsmx-nano-indoor-diy-receiver-with-cppm-pwm-spektrum-jr-multirotor-quadcopter.html

**Comment by pierrotm777** [comment]
I try to bind with a CM 703.
I have tried AUTO, DSMX and DSM2with SPIFMod  without success !
Do you try with SPIRFMod or with a 4in1 module ?

**Comment by sloped-soarer** [comment]
Thanks.
I was using SPIRFmod. No other way of testing at the moment to prove it's a receiver thing or otherwise.
SPIRFmod for DSM2 22ms binds OK, so code for that piece and CYRF6936 okay.

**Comment by Ingwie** [comment]
Hi Rich and Pierre,

DSM was the second protocol i port to OpenAVRc to try to please Mentero ....

Just one DSM2 receiver to test (Thanks @jmentero) so no DSMX tested here ....

Rich -> Could you switch to "debug mode" ;-)

**Comment by pierrotm777** [comment]
Hello Bracame,
I try again my CM703 receiver with de DSMX 22ms , DSM2 22ms and i can bind it with my TX16S but not with my OpenAVRc transmitter.
With OpenAVRc, the bind is starting, the receiver's led is blinking and after stay off.

**Comment by Ingwie** [comment]
Pierre, i said "so no DSMX tested here ...."

**Comment by sloped-soarer** [comment]
Okay. Thank you all.
So the OrangeRx R614XN receiver does not bind in DSMX mode with my OrangeRx module running Multiprotocol.
It also does not bind in DSMX when using SPIRFmod.
So in summary it looks like a receiver problem, unless i can find another transmitter to test it with.
Unless anyone has another idea, I will close the issue.

**Comment by sloped-soarer** [comment]
This gets more confusing !.
I took the same OrangeRx module which runs multiprotocol and put it in a Radio running EdgeTx.
It bound to the R614XN in DSMX 22ms mode.
The same module did not bind in a OpenAVRc transmitter using Multi or SPIRFmod.

What seems different is the binding time. Edge Tx seems to bind and complete in about four seconds.
OpenAVRc stays in bind mode until a key is pressed to exit  binding.
Maybe this prolonged bind causes the Rx to give up !.

**Comment by sloped-soarer** [comment]
The new OpenAVRc Multi Module code fixes this.  SPIRFmod code may need some more investigation.
