### ISSUE TITLE
Compiling errors in last beta 

### ISSUE THREAD

**Issue by LCMAIA** [Ingwie/OpenAVRc_Dev#8]
In order to collaborate with the development community, I use the compile-o-matic and getting theses erros... apear that iface_a7105.h has not found in the distrib version.

with option A7105 checked

make PCB=MEGAMINI LCD=SH1106 VOICE=JQ6500 EXT=FRSKY AUDIO=YES TTS=EN TRANSLATIONS=EN NAVIGATION=NO PPM_UNIT=PERCENT_PREC1 PPM=YES MULTIMODULE=YES SPIMODULES=YES CC2500=YES CYRF6936=YES NRF24l01=YES A7105=YES SDCARD=YES TEMPLATES=YES THREE_POS=POT2 SPLASH=YES UNITS=METRIC DEFAULT_MODE=2 FONT=STD BATTGRAPH=YES FAI=CHOICE AUTOSWITCH=YES AUTOSOURCE=YES FLIGHT_MODES=YES CURVES=YES PERSONAMES=YES
In file included from OpenAVRc.h:1164:0,
                 from main_avr.cpp:34:
protocol/interface.h:49:10: fatal error: iface_a7105.h: No such file or directory
 #include "iface_a7105.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:1104: OpenAVRc.elf] Error 1

with option std in telemetry checked

make PCB=MEGAMINI LCD=SH1106 VOICE=JQ6500 EXT=STD AUDIO=YES TTS=EN TRANSLATIONS=EN NAVIGATION=NO PPM_UNIT=PERCENT_PREC1 PPM=YES MULTIMODULE=YES SPIMODULES=YES CC2500=YES CYRF6936=YES NRF24l01=YES A7105=YES SDCARD=YES TEMPLATES=YES THREE_POS=POT2 SPLASH=YES UNITS=METRIC DEFAULT_MODE=2 FONT=STD BATTGRAPH=YES FAI=CHOICE AUTOSWITCH=YES AUTOSOURCE=YES FLIGHT_MODES=YES CURVES=YES PERSONAMES=YES
In file included from OpenAVRc.h:1164:0,
                 from main_avr.cpp:34:
protocol/interface.h:49:10: fatal error: iface_a7105.h: No such file or directory
 #include "iface_a7105.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:1104: OpenAVRc.elf] Error 1

**Comment by Ingwie** [comment]
Hi,
In this very beta version, A7105 and NRF24l01 are not implemented.
Compilation error correction  is done, thanks.
Expect in release but I've no model to test .
